# .github/workflows/frogbot.yml

name: "Frogbot Security Scan (User/Pass Auth via ENV)"

on:
  # 1. PULL REQUEST SCAN: Triggers on new/updated PRs
  pull_request_target:
    types: [opened, synchronize] 

  # 2. REPOSITORY SCAN: Triggers on push to the main branch
  push:
    branches:
      - main
  
  # 3. SCHEDULED REPOSITORY SCAN: Triggers periodically for autofix
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

  # 4. MANUAL TRIGGER
  workflow_dispatch:

permissions:
  # Required for Git operations (checkout) and Autofix PR creation/comments
  contents: write           
  pull-requests: write      
  # Required for uploading results to GitHub Security tab
  security-events: write    
  # Required for OIDC, but harmless here, keep if uncertain
  id-token: write           

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        # Checkout the correct commit SHA for the PR or Push
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        # Use the GitHub-provided token for checkout operations
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Run Frogbot Scan using ENV
      # Use the latest version that supports backward compatibility via ENV
      # Since you got an input error on V2, we are using the V2 tag, 
      # but relying on environment variables (JF_USER/JF_PASSWORD)
      uses: jfrog/frogbot@v2 
      env:
        # 🔑 MANDATORY JFROG AUTHENTICATION (PASSED VIA ENVIRONMENT)
        # The Frogbot CLI often detects these environment variables
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        
        # 🔑 MANDATORY GITHUB TOKEN (For Pull Request and Autofix operations)
        # It is highly recommended to use a GitHub Personal Access Token (PAT)
        # for this, stored in secrets.JF_GIT_TOKEN, as GITHUB_TOKEN has limitations.
        JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
        
        # Optional: Add any other required Frogbot environment variables here
        # E.g., JF_PROJECT: 'my-jfrog-project'
        # E.g., JF_DEPS_REPO: 'npm-virtual'
